Fixed path being drawn in river
However there is an issue with when the two paths cross over, causing the game to crash with:
java.util.NoSuchElementException: Queue is empty.

Also, the way the trails render means one trail always shows above the others